### ISSUE TITLE
Can't seem to get upgrade to p2p to work

### ISSUE THREAD

**Issue by joshterrill** [socketio/socket.io-p2p#10]
I've got the example chat up and running by following the instructions, but when I initiate the server and try to press "Go Private", I see "WebRTC connection established!" in the window but not in the other window that I've opened... however if I press "Go Private" on both of them, no messages get sent across at all. Has anyone else ran into this? Is there an actual hosted working example of the chat app somewhere?

**Comment by tomcartwrightuk** [comment]
Is this still an issue? I thought I may have seen on Twitter that you had solved it?

**Comment by joshterrill** [comment]
No longer an issue I solved it.
