### ISSUE TITLE
Consistency

### ISSUE THREAD

**Issue by bevacqua** [socketio/socket.io-p2p#6]
Why not provide a `new`-less implementation just like `socket.io` does?

```js
var socket = io();
var p2p = new P2P(socket);
```

```js
var socket = io();
var p2p = P2P(socket);
```

**Comment by tomcartwrightuk** [comment]
This is a good idea. I will investigate how this can be done. Will keep this issue open to remind to look into it.

**Comment by tomcartwrightuk** [comment]
I will revisit this, but there would be a fair bit of wrangling required to get it to work and it's not a massive priority. Version 2.0 might be a good time to do so.
